trigger: none

pool:
  name: 'DemoAgentPool'

steps:
- script: |
    echo "Install dependencies"
    # Add commands to install dependencies
  displayName: 'Install dependencies'

- script: |
    echo "Build your project"
    # Add commands to build your project
  displayName: 'Build project'

- script: |
    echo "Run tests"
    # Add commands to run your tests
  displayName: 'Run tests'
