parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

variables:
  name: exampleParameter
    ${{ if eq(variables['Build.Reason'], 'Schedule')}}:
      value: 'Schedule'
    ${{ else }}:
      value: ${{parameters.exampleParameter}}



steps:
- script: echo ${{parameters.exampleParameter}}
  displayName: 'Echo custom parameter'