trigger: none

schedules:
- cron: "30 2 * * 0"
  displayName: "Every Saturday at 8:30 PM CST"
  branches:
    include:
    - main
  always: true

pool:
  name: 'DemoAgentPool'

steps:
- script: |
    echo "Install dependencies"
    # Add commands to install dependencies
  displayName: 'Install dependencies'

- script: |
    echo "Build your project"
    # Add commands to build your project
  displayName: 'Build project'

- script: |
    echo "Run tests"
    # Add commands to run your tests
  displayName: 'Run tests'
