parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

variables:
  parameterValue: ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
                    'Scheduled Default Value'
                  ${{ if ne(variables['Build.Reason'], 'Schedule') }}:
                    ${{ parameters.exampleParameter }}

steps:
- script: echo ${{parameters.exampleParameter}}
  displayName: 'Echo custom parameter'