parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

steps:
- script: echo ${{ parameters.exampleParameter }}
  displayName: 'Echo custom parameter'
