parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

variables:
  ${{ if eq(variables['Build.Reason'], 'Schedule')}}:
    exampleParameter: 'Schedule'

steps:
- script: echo ${{parameters.exampleParameter}}
  displayName: 'Echo custom parameter'