parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

variables:
  exampleParameter: ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
                      'Schedule'
                    ${{ else }}:
                      ${{ parameters.exampleParameter }}

steps:
- script: echo ${{parameters.exampleParameter}}
  displayName: 'Echo custom parameter'