parameters:
- name: exampleParameter
  type: string
  default: 'Hello World'

trigger: none

pool:
  name: 'DemoAgentPool'

variables:
  # Set the exampleParameter to 'Schedule' if the build reason is 'Schedule'
  ${{ if eq(variables['Build.Reason'], 'Schedule')}}:
    exampleParameter: 'Schedule'
  # Otherwise, use the provided exampleParameter
  ${{ if ne(variables['Build.Reason'], 'Schedule')}}:
    exampleParameter: ${{parameters.exampleParameter}}


steps:
- script: echo ${{parameters.exampleParameter}}
  displayName: 'Echo custom parameter'